### ISSUE TITLE
fatal: Could not read from remote repository. Please make sure you have the correct access rights

### ISSUE THREAD

**Issue by cequintana** [bmatcuk/bmatcuk.github.io#1]
I keep getting this error when I attempt to build fossa-cli.  Thoughts?

Solving failure:                                                                         (1) failed to clean up git repository at C:\Users\cquintana\go\pkg\dep\s ources\https---github.com-bmatcuk-doublestar - dirty? corrupted? status output:   M test/broken-symlink                                                                                                                                                    (2) failed to list versions for ssh://git@github.com/bmatcuk/doublestar:  git@github.com: Permission denied (publickey).                                  fatal: Could not read from remote repository.                                                                                                                     Please make sure you have the correct access rights                              and the repository exists.                                                       : exit status 128                                                                        (3) failed to clean up git repository at C:\Users\cquintana\go\pkg\dep\s ources\git---github.com-bmatcuk-doublestar - dirty? corrupted? status output:     M test/broken-symlink                                                                                                                                                    (4) failed to clean up git repository at C:\Users\cquintana\go\pkg\dep\s ources\http---github.com-bmatcuk-doublestar - dirty? corrupted? status output:    M test/broken-symlink
--

**Comment by bmatcuk** [comment]
@cequintana: This issue belongs in bmatcuk/doublestar - I've created an [issue over there](https://github.com/bmatcuk/doublestar/issues/22) and I'm going to close this.

**Comment by cequintana** [comment]
oh ok thank you for the assist!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
